site_name: Milo Wiki
site_url: https://nicolamilani.it/wiki


site_author: Nicola Milani
site_description: "Appunti per non dimenticare"

theme:
  name: material

markdown_extensions:
  - admonition
  - toc:
      permalink: true